<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH . '/libraries/REST_Controller.php';


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Uocb
 *
 * @author Richard
 */


class Uocb extends REST_Controller
{
    function __construct()
        {
            // Construct the parent class
            parent::__construct();

            // Configure limits on our controller methods
            // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
            $this->methods['result_get']['limit'] = 500; // 500 requests per hour per user/key
            $this->methods['result_post']['limit'] = 100; // 100 requests per hour per user/key
            $this->methods['result_delete']['limit'] = 50; // 50 requests per hour per user/key
        }
        
        // todo: return a single result 
        public function result_get() 
        {
            
            if(!$this->get('result_id'))
                {
                    $this->response(NULL, 400);
                }
            
            //todo: access model and retrieve result    
                
             $data = array('returned: '. $this->get('result_id')); // for debug, repeat result_id back 
             
             $this->response($data); // return data to the browser
             
            
            
            
        }
        // todo: return top results such as for the leaderboard
        public function results_get()
        {
           //student_id - such as for 'my best times'
           //gender
           //grade
           //period - daily, weekly (last 7 days), monthly(current month)
            
            $data = array('returned:');
             
             $this->response($data); // return data to the browser
            
            
            
        }
        
        // todo: add a result to the database
        public function result_post()
        {
                // $this->some_model->update_user( ... );
            $message = [
                'result_id' => 100, // Automatically generated by the model
                'date' => $this->post('date'),
                'time' => $this->post('time'),
                'ranked' => $this->post('ranked'),
                'flagged' => $this->post('flagged'),
                'student_id' => $this->post('student_id'),

//                'name',
//                'gender',
//                'grade',
                
                
                'message' => 'test post of a result'
            ];

            $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }
        
        //remove a result, admin only
        public function result_delete()
        {
            
            // todo: Validate administration rights
            
            $result_id = (int) $this->get('result_id');

            // Validate the result_id.
            if ($result_id <= 0)
            {
                // Set the response and exit
                $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
            }

            // $this->some_model->delete_something($id);
            $message = [
                'result_id' => $result_id,
                'message' => 'Test Deleted the result'
            ];

            $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
        }
    
}
